package main

import (
	"net/http"

	"github.com/labstack/echo/v4"
	_ "github.com/layardaputra/echo-swag/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/layardaputra/echo-swag/src/book"
	"github.com/layardaputra/echo-swag/src/user"

	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title Echo Swag API Documentation
// @version 1.0
// @description Sample Documentation of Echo Swag.

// @host echo-swag-layarda-test.com
// @BasePath /v1
func main() {
	r := echo.New()

	book.RegisterBookRoute(r)
	user.RegisterUserRoute(r)

	r.GET("/", func(ctx echo.Context) error {
		data := "Hello from /index"
		return ctx.String(http.StatusOK, data)
	})

	r.GET("/swagger/*", echoSwagger.WrapHandler)

	r.Start(":8000")
}
